### ISSUE TITLE
ImportError: cannot import name 'triu' from 'scipy.linalg'

### ISSUE THREAD

**Issue by AishAmalgam** [urchade/GLiNER#52]
After installing 'gliner' using the command "pip install gliner",  I received the following message: "Successfully installed flair-0.13.1 gliner-0.1.6" But I encountered the following error message when attempting to load the model with the following code:

from gliner import GLiNER  
model = GLiNER.from_pretrained("urchade/gliner_base")

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/gliner/__init__.py", line 3, in <module>
    from .model import GLiNER
  File "/usr/local/lib/python3.11/site-packages/gliner/model.py", line 13, in <module>
    from gliner.modules.token_rep import TokenRepLayer
  File "/usr/local/lib/python3.11/site-packages/gliner/modules/token_rep.py", line 4, in <module>
    from flair.data import Sentence
  File "/usr/local/lib/python3.11/site-packages/flair/__init__.py", line 42, in <module>
    from . import (  # noqa: E402 import after setting device
  File "/usr/local/lib/python3.11/site-packages/flair/models/__init__.py", line 1, in <module>
    from .clustering import ClusteringModel
  File "/usr/local/lib/python3.11/site-packages/flair/models/clustering.py", line 14, in <module>
    from flair.embeddings import DocumentEmbeddings
  File "/usr/local/lib/python3.11/site-packages/flair/embeddings/__init__.py", line 13, in <module>
    from .document import (
  File "/usr/local/lib/python3.11/site-packages/flair/embeddings/document.py", line 16, in <module>
    from flair.embeddings.token import FlairEmbeddings, StackedEmbeddings, TokenEmbeddings
  File "/usr/local/lib/python3.11/site-packages/flair/embeddings/token.py", line 10, in <module>
    import gensim
  File "/usr/local/lib/python3.11/site-packages/gensim/__init__.py", line 11, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, utils  # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gensim/corpora/__init__.py", line 6, in <module>
    from .indexedcorpus import IndexedCorpus  # noqa:F401 must appear before the other classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gensim/corpora/indexedcorpus.py", line 14, in <module>
    from gensim import interfaces, utils
  File "/usr/local/lib/python3.11/site-packages/gensim/interfaces.py", line 19, in <module>
    from gensim import utils, matutils
  File "/usr/local/lib/python3.11/site-packages/gensim/matutils.py", line 20, in <module>
    from scipy.linalg import get_blas_funcs, triu
ImportError: cannot import name 'triu' from 'scipy.linalg' (/usr/local/lib/python3.11/site-packages/scipy/linalg/__init__.py)

Additionally, when attempting to run "python -c 'import gliner; print(gliner.version)'", I encountered the same ImportError.

**Comment by urchade** [comment]
See https://github.com/urchade/GLiNER/issues/50

**Comment by AishAmalgam** [comment]
> See #50
resolved, thanks
